### ISSUE TITLE
ToDo: plot multiple simulations 

### ISSUE THREAD

**Issue by fischer-fjd** [fischer-fjd/RconTroll#1]
Two options:
- generic plot function with TROLLoutput or TROLLstacks
- separate routines

**Comment by sylvainschmitt** [comment]
Done in `RconTroll 0.1.9005` but can still be improved...

# RconTroll 0.1.9005

* New possibilities in plotting `what` argument (agb, gpp, litterfall, all abund, all ba, all R, all final_pattern, all disturbance)
* `inventoryFromOutput` fixed
* Joining `plot` methods in one file with only one doc
* Joining `print` methods in one file with only one doc
* Joining `summary` methods in one file with only one doc
* Corrected all WARNINGs and NOTEs in R CMD check
* Corrected part of `goodpractice::gp()` recomendations
* Add `cran-comment.md` to justify R CMD check NOTEs
