### ISSUE TITLE
ToDo: Summary

### ISSUE THREAD

**Issue by fischer-fjd** [fischer-fjd/RconTroll#2]
Generic summary function

**Comment by sylvainschmitt** [comment]
Done in `RconTroll 0.1.9003`

# RconTroll 0.1.9003

* renaming objects and methods (e.g. `TROLLoutput` to `TROLLsim`, `virtualizeFromData` to `inventoryFromData`, etc.)
* definition of `summary` for class TROLLsim
* new class TROLLsimstack (with methods `print` and `summary`, the latter not yet fully implemented)

But can still be improved
