### ISSUE TITLE
`loadOutput` with empty data frame

### ISSUE THREAD

**Issue by sylvainschmitt** [fischer-fjd/RconTroll#5]
We  need to improve data loading in `loadOutput` function for empty data frames (for instance some models don't produce data for _0_death1.txt).

I will try to do it. I let this issue open as a reminder

**Comment by Riodinino** [comment]
In the output's path :
lisfil = list.files(pattern = '//.txt$')
info = file.info(lisfil)
empty = rownames(info[info$size == 0, ])

Would it do the job ?

**Comment by Riodinino** [comment]
and then 
if(!(paste0(name,"_0_death.txt") %in% empty) { #do stuff}
else{death = list()} #or whatever default to this case

**Comment by sylvainschmitt** [comment]
Related to issue #12 , will be treated soon
