### ISSUE TITLE
Error in LoadOutput

### ISSUE THREAD

**Issue by Riodinino** [fischer-fjd/RconTroll#9]
https://github.com/sylvainschmitt/RconTroll/blob/72ecf8793abed1572f8aabf783493a95ffae7c41/R/loadOutput.R#L95

    #### Full final ####
    full_final <- suppressWarnings(
      try(read.table(file.path(path, paste0(name, '_0_fullfinal.txt'))), 
          silent = TRUE))
    **if(inherits(disturbance, 'try-error'))** should be if(inherits(**full_final**, 'try-error'))

**Comment by sylvainschmitt** [comment]
Related to new issue #12 , will be treated soon
